### ISSUE TITLE
Theme color pallet will not fully appear

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/ecobit#1]
The themes color pallet will not fully appear : 
https://prnt.sc/uw5dcj

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
